[automount]
# https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-settings
enabled = true
mountFsTab = true
root = /mnt/
options = "metadata,uid=1003,gid=1003,umask=077,fmask=11,case=off"

[boot]
# https://learn.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings
systemd = true

[interop]
# https://learn.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings
enabled = true
appendWindowsPath = true

[network]
# https://learn.microsoft.com/en-us/windows/wsl/wsl-config#network-settings
generateHosts = true
generateResolvConf = true

[user]
# https://learn.microsoft.com/en-us/windows/wsl/wsl-config#user-settings
#default =
